version: 0.1

phases:
  install:
    commands:
      - echo installing nodejs....working......
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
  pre_build:
    commands:
      #- sed -i "s|MONGODB_URI=.*|MONGODB_URI='$Mongouri'|g" .env
      - sed -i "s|NODE_ENV.*|NODE_ENV=production|g" .env
      - sed -i "s|DB_HOST.*|DB_HOST=demodb|g" .env
      - sed -i "s|DB_USER.*|DB_USER=naman|g" .env
      - sed -i "s|DB_PASS.*|DB_PASS=namanpande12345|g" .env
  build:
    commands:
      - echo building...
      - npm install
       
  post_build:
    commands:
      - chmod +x Appstop.sh Appstart.sh  
       
artifacts:
  files:
    - "**/*"
